### ISSUE TITLE
Still the error

### ISSUE THREAD

**Issue by Altraze** [egg82/AdvancedEnchantments#13]
19:54:55 [Server] ERROR Could not pass event PlayerAnimationEvent to AdvancedEnchantments v4.15.20
03.08 19:54:55 [Server] INFO java.lang.NoClassDefFoundError: org/apache/commons/lang3/Validate
03.08 19:54:55 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.invokeSendPacket(ChannelInjector.java:651) ~[?:?]
03.08 19:54:55 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.sendServerPacket(ChannelInjector.java:640) ~[?:?]
03.08 19:54:55 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector$4.sendServerPacket(ProtocolInjector.java:403) ~[?:?]
03.08 19:54:55 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:786) ~[?:?]
03.08 19:54:55 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:740) ~[?:?]
03.08 19:54:55 [Server] INFO at me.egg82.ae.hooks.ProtocolLibHook.sendMulti(ProtocolLibHook.java:190) ~[?:?]
03.08 19:54:55 [Server] INFO at me.egg82.ae.hooks.ProtocolLibHook.sendFake(ProtocolLibHook.java:126) ~[?:?]
03.08 19:54:55 [Server] INFO at me.egg82.ae.events.enchants.MirageEvents.raise(MirageEvents.java:121) ~[?:?]
03.08 19:54:55 [Server] INFO at me.egg82.ae.events.enchants.MirageEvents.swing(MirageEvents.java:77) ~[?:?]
03.08 19:54:55 [Server] INFO at ninja.egg82.events.SingleEventSubscriber.call(SingleEventSubscriber.java:100) ~[?:?]
03.08 19:54:55 [Server] INFO at ninja.egg82.events.BukkitEventSubscriber.call(BukkitEventSubscriber.java:50) ~[?:?]
03.08 19:54:55 [Server] INFO at ninja.egg82.events.BukkitEventSubscriber.lambda$new$0(BukkitEventSubscriber.java:31) ~[?:?]
03.08 19:54:55 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.14.4.jar:git-Paper-156]
03.08 19:54:55 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-156]
03.08 19:54:55 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-156]
03.08 19:54:55 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1843) ~[patched_1.14.4.jar:git-Paper-156]
03.08 19:54:55 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInArmAnimation.a(SourceFile:32) ~[patched_1.14.4.jar:git-Paper-156]
03.08 19:54:55 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInArmAnimation.a(SourceFile:9) ~[patched_1.14.4.jar:git-Paper-156]
03.08 19:54:55 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-156]
03.08 19:54:55 [Server] INFO at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-156]
03.08 19:54:55 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-156]
03.08 19:54:55 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-156]
03.08 19:54:55 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-156]
03.08 19:54:55 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1012) ~[patched_1.14.4.jar:git-Paper-156]
03.08 19:54:55 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1005) ~[patched_1.14.4.jar:git-Paper-156]
03.08 19:54:55 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-156]
03.08 19:54:55 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:989) ~[patched_1.14.4.jar:git-Paper-156]
03.08 19:54:55 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:922) ~[patched_1.14.4.jar:git-Paper-156]

**Comment by egg82** [comment]
Definitely an issue with ProtocolLib, here, and not AE. AE just hooks ProtocolLib, which is where the issue actually is. The only reason you're seeing AE in the error at all is because it's simply the plugin that called that particular method. Any plugin could have been the cause; it just happened to be AE in this instance.

1. Verify that you are running the correct version of ProtocolLib for your server version. For 1.14.4, it should be downloaded from the official Jenkins [here](http://ci.dmulloy2.net/job/ProtocolLib%20Gradle/lastStableBuild/)
2. Ensure you aren't using a plugin manager such as PlugMan, which has a reputation for [exactly this issue](https://www.spigotmc.org/threads/protocollib.36230/page-54)
3. Make sure you aren't running `/reload` on the server, as that will definitely cause issues with many plugins, not just ProtocolLib (AE, coincidentally, will handle this fine. The server will not.)

[Here's another post with your same issue](https://www.reddit.com/r/admincraft/comments/ci1brn/plugins_dk_if_this_fits_here/?ref=readnext) if all of the above somehow don't solve it.
