### ISSUE TITLE
Enchantments not showing up

### ISSUE THREAD

**Issue by sinsoffallengods** [egg82/AdvancedEnchantments#14]
Enchants are not showing in the enchanting table as an option(set to .5 in the config for a 50% chance). They dont show as an option and seem to just overwrite enchants instead. For example a protection 4 enchant has a chance to become any one of your enchants from the plugin, overwhelmingly seeming to prefer soulbound 1. If I could get them to show in the game on the enchanting table that would be great!

**Comment by egg82** [comment]
I'm not sure what you mean by "show in the game on the enchanting table" since the enchanting table is obfuscated. The plugin does replace X% of vanilla enchants (defined by config) from the enchanting table to attempt to keep balance (instead of adding them).

I've gone ahead and implemented a small fix for the randomness/level issue, however. Give the newest build a try and see if that fixes things.

https://jenkins.egg82.me/job/egg82/job/AdvancedEnchantments/job/master/

**Comment by sinsoffallengods** [comment]
This appears to have fixed the randomness, as the enchants are being replaced as they should be but with fair returns, Protection 4 gives repairing 3 or similar instead of soulbound 1
