### ISSUE TITLE
AdvancedEnchantments not working

### ISSUE THREAD

**Issue by reflezion** [egg82/AdvancedEnchantments#17]
Plugin version: '4.18.23'
Server type: 'Spigot (Beerspigot)'
Server version: '1.8'

**Describe the bug**
The plugin does not work at all. It is red in the /plugins menu 

**Expected behavior**
The plugin to work

**To Reproduce**
1. Install the plugin
2. Start the server
3. Click on '....'

**Screenshots**
https://paste.helpch.at/wuwicupusu.md
Im not getting anything else from AdvancedEnchants in the console then this.

**Additional context**
I keep getting errors

**Comment by egg82** [comment]
I wonder what BeerSpigot has that [TacoSpigot](https://github.com/TacoSpigot/TacoSpigot) doesn't? It's hard to come up with reasons to use random "performance" forks when you're sticking with 1.8

Basically, it would be difficult to impossible for me to support every fork of CB/Spigot/Paper out there. I currently support CraftBukkit, Spigot, Paper, and TacoSpigot, but that's about as far as I'll go on that.

Something inside Beerspigot is screwing with AE - most of these "performance" forks are just Spigot with certain plugins built-in, and who-knows-what-else going on behind-the-scenes. In this case, it's not happy with the way that AE injects into itself (most likely, though since they seem to have killed the logger as well it's hard to tell)

Closing this one as WONTFIX - try TacoSpigot or - even better - Paper.

**Comment by reflezion** [comment]
Will there ever be support for BeerSpigot?

**Comment by egg82** [comment]
Considering I'd either have to buy it or download a pirated copy.. Probably not, no.
Additionally, I fundamentally dislike those kinds of paid forks - so it's also a principal thing. They rarely, if ever, are actually worth the money.

**Comment by reflezion** [comment]
If you want I can send you my beerspigot jar file. because I kind of purchased this plugin to work on my server with Beerspigot and I wont use advancedenchantments on any other type of server than factions and on my factions servers I always use forks.

**Comment by egg82** [comment]
I took a look at TacoSpigot and it seems there's an error with it loading there - I'll fix it and you can see if that fix works on BeerSpigot as well.

**Comment by egg82** [comment]
Fixed in db144f6 - check latest Jenkins for build:
https://jenkins.egg82.me/job/egg82/job/AdvancedEnchantments/job/master/
