### ISSUE TITLE
4.19.24 and 4.19.25 bugs

### ISSUE THREAD

**Issue by HexaMark** [egg82/AdvancedEnchantments#26]
Plugin version: '4.19.24 and 4.19.25'
Server type: 'Paper-237'
Server version: '1.14.4'

**Describe the bug**
4.19.25 doesn't work correctly. Enchants can not be found in the wild, /enchanter and it's subcommands do not work at all regardless of config setting. In 4.19.24, enchantments deteriorate over time or depending on how many enchants were done since the last restart. For example, eventually, the plugin will begin choosing an enchantment between its given weight values and will ALWAYS return the same enchantment, even if it's not compatible with the item being enchanted inside the table. For example, the console (with debug) repeatedly tries to apply aerial to a shovel, fails and only ever provides vanilla enchants. Additionally, sometimes enchanting an item will not make the "item enchanted sound", will apply a custom enchant and then take 30 levels from the player (Even though that's not possible in modern Minecraft). Use event.whichButton() to fix that one <--. There's the issue with level 4 + level 4 = level 5 and Unbreaking 1 too

**Expected behavior**
I expect the plugin to work, without giving so many bugs

**To Reproduce**
It's random

**Plugins**
AdvancedEnchantments, AdvancedGift, AdvancedPortals, AsyncWorldEdit, AuctionHouse, AutoSaveWorld, BigDoors, Citizens, CitizensCMD, ClearLag, ColoredSigns, CoreProtect, CraftingStore, CustomGUI, DeadChest, DiscordSRV, Essentials, EssentialsChat, EssentialsSpawn, Factions, FastAsyncWorldEdit, GCore, HolographicDisplays, JupiterCore, LagAssist, LimitPillagers, LuckPerms, MaintenanceSpigot, MassiveCore, McCombatLevel, mcMMO, MorphRedeem, MovingDevApi, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, MyCommand, NoFireworkDamage, NoPhantoms, NoteBlockAPI, PlaceholderAPI, PluginConstructorAPI, ProPackages, ProtocolLib, PVPControl, RandomTeleport, SAML, Scoreboard-revision, Sentinel, ServerRestorer, SharpnessDamageIncreaser, ShopGUIPlus, sleep-most, SlotMachineGUI, SpecializedCrates, SuperVanish, TAB, TokenManager, UltimateAutoRestart, Vault, ViaVersion, VillagerOptimiser, VoidGenerator, WorldEdit, WorldEditSelectionVisualizer, WorldGuard, XPBoost

**Screenshots/Video**
None

**Additional context**
None

**Comment by egg82** [comment]
`/enchanter` isn't part of AE, but instead part of [this plugin](https://www.spigotmc.org/resources/%E2%9C%85-advancedenchantments-%E2%9D%8C-create-custom-enchants-%E2%9C%85-35-sale.43058/) by the same name. It's confusing, I know, and that was an oversight on my end when I created the plugin.

I'll take a look at the weights again. I can definitely see why it might try to choose the same enchant for an item over and over again since that's how it was designed. It only takes into account applied enchants when considering weight. Definitely another oversight on my part- I didn't consider that some players might not enchant particular types of items for some time and favor others instead.

I'll also take a look at the levels and see what exactly might be causing that, or if it's even a bug at all.

Thanks for the report!

**Comment by HexaMark** [comment]
Thank you for a quick response. I would like to reassure you that the levels thing is a bug. It does not happen all the time, when plugin works fine it enchants and takes 3 levels from the player whilst also playing the sound effect. When it bugs out, it plays no sound, enchants and then removes 30 levels. By the way, you did not mention anything about the item combining bug 4lvl+4lvl=5lvl+unbreaking 1.
