### ISSUE TITLE
Enchantments are periodically not working. 

### ISSUE THREAD

**Issue by BluLightShow** [egg82/AdvancedEnchantments#7]
I've given all of the correct permission nodes to my players yet enchantments like antigravity and others are periodically not working. We're using the latest towny pre-release. This might have something to do with players storing their enchanted armor items in their ender chests using the essentials "/enderchest" command. They notice that after storing it there and taking it out the custom enchantments seem to not be working, but randomly after some time, they begin to work again if they don't store them in their ender chests again.

**Comment by egg82** [comment]
Just tested antigravity on the latest Paper 1.14.4, seems to work fine after being added and removed from EssX's `/ec`. Keep in mind it can take up to 3 seconds (60 server ticks, so maybe longer if your server is lagging) to apply the effect that antigravity gives when putting the boots back on. This is intentional to save your server some resources.

If you have other examples, maybe a video, I'd love to see them. It's difficult to diagnose this problem if it exists though. I'll leave the issue open for now.

**Comment by egg82** [comment]
Closing for now. Re-open if needed.
